wrap_comments = true
imports_granularity = "One"
group_imports = "One"
format_code_in_doc_comments = true
error_on_line_overflow = true
error_on_unformatted = true
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
float_literal_trailing_zero = "IfNoPostfix"
imports_layout = "Vertical"
normalize_comments = true
reorder_impl_items = true
struct_lit_single_line = false
style_edition = "2024"
trailing_comma = "Never"
use_try_shorthand = true
where_single_line = true
fn_single_line = true