[package]
name = "smallvec-fuzz"
version = "0.0.0"
authors = ["The Servo Project Developers"]
edition = "2018"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1.4", features = ["derive"] }
libfuzzer-sys = "0.4"
smallvec = { path = "..", features = ["const_generics"] }

[[bin]]
name = "main"
path = "fuzz_targets/main.rs"
test = false
doc = false
bench = false