[package]
name = "smallvec-fuzz"
version = "0.0.0"
authors = ["The Servo Project Developers"]
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1.4", features = ["derive"] }
libfuzzer-sys = "0.4"

[dependencies.smallvec]
features = ["const_generics"]
path = ".."

[[bin]]
name = "main"
path = "fuzz_targets/main.rs"
test = false
doc = false
bench = false