name: checks
on:
  pull_request:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
jobs:
  stable:
    name: Stable
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: install
        uses: dtolnay/rust-toolchain@stable
      - name: test no default features
        run: cargo test --no-default-features
      - name: test default features
        run: cargo test
      - name: fuzz
        working-directory: fuzz
        run: |
          sudo apt-get update -y
          sudo apt-get install -y binutils-dev libunwind8-dev libcurl4-openssl-dev 
          sudo apt-get install -y libelf-dev libdw-dev cmake gcc libiberty-dev
          ./travis-fuzz.sh
  nightly:
    name: Nightly
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: install
        uses: dtolnay/rust-toolchain@nightly
      - name: style check
        run: |
          rustup component add rustfmt
          cargo fmt --all --check
      - name: clippy check
        run: |
          rustup component add clippy
          cargo clippy 
      - name: doc build
        run: cargo doc --all-features
      - name: test no default features
        run: cargo test --no-default-features
      - name: test default features
        run: cargo test
      - name: test all features
        run: cargo test --all-features
      - name: miri no default features
        run: |
          rustup component add miri
          cargo miri test --no-default-features
      - name: miri default features
        run: cargo miri test
      - name: miri all features
        run: cargo miri test --all-features
      - name: bench no default features
        run: cargo bench --no-default-features
      - name: bench default features
        run: cargo bench
      - name: bench all features
        run: cargo bench --all-features
  nostd:
      name: NoStd
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v7
        - name: install
          uses: dtolnay/rust-toolchain@stable
          with:
            target: thumbv7m-none-eabi
        - name: test no default features
          run: cargo test --no-default-features
        - name: test default features
          run: cargo test
  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: install
        uses: dtolnay/rust-toolchain@1.86
      - name: test no default features
        run: cargo test --no-default-features
      - name: test default features
        run: cargo test