name: fuzzing

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  fuzz:
    name: Fuzz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo dependencies, binaries and target directory
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "fuzz"

      - name: Install cargo-fuzz
        run: which cargo-fuzz || cargo install cargo-fuzz

      - name: Restore fuzzing corpus
        uses: actions/cache/restore@v6
        with:
          path: fuzz/corpus
          key: fuzz-corpus-${{ github.run_id }}
          restore-keys: |
            fuzz-corpus-

      - name: Run fuzzing for 30 minutes
        run: cargo fuzz run main -- -max_total_time=1800

      - name: Minimize corpus
        if: always()
        run: cargo fuzz cmin main

      - name: Save updated corpus
        if: always()
        uses: actions/cache/save@v6
        with:
          path: fuzz/corpus
          key: fuzz-corpus-${{ github.run_id }}
