name: fuzzing
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  fuzz:
    name: Fuzz
    if: github.repository == 'servo/rust-smallvec'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: install
        uses: dtolnay/rust-toolchain@stable
      - name: fuzzing
        run: |
          sudo apt-get update -y
          sudo apt-get install -y binutils-dev libunwind8-dev libcurl4-openssl-dev 
          sudo apt-get install -y libelf-dev libdw-dev cmake gcc libiberty-dev
          ./travis-fuzz.sh