name: fuzzing
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  fuzz:
    name: Fuzz
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: install rust nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: restore corpus
        uses: actions/cache/restore@v6
        with:
          path: fuzz/corpus
          key: fuzz-corpus-${{ github.run_id }}
          restore-keys: |
            fuzz-corpus-
      - name: fuzz for 30 minutes
        run: cargo fuzz run main -- -max_total_time=1800
      - name: minimize corpus
        if: always()
        run: cargo fuzz cmin main
      - name: save corpus
        if: always()
        uses: actions/cache/save@v6
        with:
          path: fuzz/corpus
          key: fuzz-corpus-${{ github.run_id }}
